### ISSUE TITLE
General Error Module not accessible

### ISSUE THREAD

**Issue by clipkey** [phpbb-extensions/pages#116]
Help please. Using phpbb 3.1.8. When I install and try to setup in the "Extensions/PAGES/Manage Pages" I get this:
************
General Error
Module not accessible

BACKTRACE

FILE: (not given by php)
LINE: (not given by php)
CALL: msg_handler()

FILE: [ROOT]/includes/functions_module.php
LINE: 563
CALL: trigger_error()

FILE: [ROOT]/adm/index.php
LINE: 81
CALL: p_master->load_active()

**Comment by DavidIQ** [comment]
As per the readme file in this repo you need to post in the support area:
https://www.phpbb.com/customise/db/extension/pages/support
