### ISSUE TITLE
Having a different theme than the default one

### ISSUE THREAD

**Issue by sylvaindurand** [phpbb-extensions/pages#120]
Hello!

Let's say I have two themes: `prosilver` (the default one) and `mytheme`, for selected subforums. 

It would be great to be able to create a page with `mytheme`.

But, if I create `page_mytheme.html` in `styles/mytheme/template`, I can select it in the admin, but the page won't be rendered. The error message is:

> Unable to find template "pages_mytheme.html" (looked into: ./ext/phpbb/pages/styles/prosilver/template, ./ext/phpbb/pages/styles/prosilver/theme, ./styles/prosilver/template, ./styles/prosilver/theme).```

Thank you very much!

**Comment by VSEphpbb** [comment]
Support can be found where you downloaded this extension at https://www.phpbb.com/customise/db/extension/pages

**Comment by sylvaindurand** [comment]
Thank you for your answer; as it looked like a bug to me, I posted here. Sorry!
