### ISSUE TITLE
Preview button

### ISSUE THREAD

**Issue by Galixte** [phpbb-extensions/pages#149]
Hi @VSEphpbb,

is it possible to add the preview feature on editor page for this extension?

**Comment by Galixte** [comment]
@kasimi, @Derky what to you think?

**Comment by VSEphpbb** [comment]
It's not done because, on the one hand it really complicates the code, but also because the look is very influenced by the template file used, which is all contained outside of the ACP, so to try and preview it in the ACP would be an inaccurate display.

**Comment by Galixte** [comment]
ok, I understand, and what about from the editor page to have a link to open a popup/windows to the page Is it possible?

No, i'm stupid i need to submit the editor page to view the result. I just finish to publish on a board more than a hundred pages with this extension and the only one bad point is the preview.

So, thanks you.
