### ISSUE TITLE
[REQ] Multi language support for custom pages

### ISSUE THREAD

**Issue by jakubsuchygit** [phpbb-extensions/pages#56]
Hello,
I would like to suggest to you to add new feature for this extension. It would be exactly same as for your other extension "Rules". 
The new feature could look like this:
When you are about to manage your pages in ACP you will be prompted to select for what [installed] language you will be managing pages.
As for db implementation. I would suggest to add new column 'language' to the table 'prefix_pages'.

I hope you will create this feature, because I think it will really enhance the possibilities of phpbb for all.

Thank you. Biosek.

**Comment by David-NF** [comment]
Interesting thought, but what about the page link would you have separate links for different languages? Or just one link but with multi language content? I would prefer that last option, but I don't really need it, just interesting ;)

**Comment by jakubsuchygit** [comment]
Yeah my first idea was to create 2 separate menus for 2 languages. But yes the option where you have only one menu in different languages is good enough too :).

**Comment by jakubsuchygit** [comment]
That indeed makes sense. However static content of the forum could be for example tutorials, help, support. I think that this is the reason why I came up with this, because forum has some native language, but when forum wants to support bigger audience, it would make sense to have forum with native language, sections for other languages and everything static multi-lingual.

For example our forum is natively in Czech. With our servers we are expanding for bigger audience and we would like to support english speaking people. For this purpose It would be great help, if pages could be multi-lingual. 

In the end I agree, that it would be a little more difficult in ACP, but I don't think that it would be a deal breaker or annoying for administrators.

In the end, if you won't support this I will end up making it by myself :)

**Comment by DavidIQ** [comment]
I think if you provide necessary event locations for what you want to do we can incorporate those into a future release.

**Comment by jakubsuchygit** [comment]
Well I was thinking about it and in my opinion the easiest way would be like this:
1. add migration to 'alter table prefix_pages add column lang;'
2. to ACP table where you print all created pages i would add new column to the table for language
3. in form of adding or editing page i would create new field 'For language: combobox'
4. i think in controller/admin_controller/add_edit_page_data i would add that new field for saving to db
5. next i cant find where it is, but when you render links to navbars there should be filter that renders only those links which has set language as current forum language
6. that should be it. this should be the easiest way of doing it. the only downside is that if someone support 10 languages for him to incorporate static pages to all pages he has to create the same page 10 times more. so there might be a good idea to add to combobox option 'all' which would mean for all languages

I think no event locations are needed.

**Comment by VSEphpbb** [comment]
It's actually not that easy, nor can it be handled as an add-on, as the language has to be tracked through every ACP interaction and would require a heavy rewrite of the ACP section and most of its methods.

The fact is you can already do multi-lingual pages with this extension, and quite simply too.

Instead of creating the content portion via the ACP, put your content directly into your own custom template files for your pages. You can use the var `S_USER_LANG` to display different content based on the language the user is using. For example:
```
<!-- IF S_USER_LANG eq 'fr' -->
My page content in French goes here
<!-- ELSE -->
My page content in the board default lang goes here
<!-- ENDIF -->
```
There are very detailed DOCs on how to make your own page templates in the README here and in the official support forum FAQ section. It supports HTML code so you have the freedom to make the page do anything you want it to.

We put a lot of effort into making this extension very customisable for situations just like this.

**Comment by jakubsuchygit** [comment]
Wow, I had some similar idea, but couldn't find if it is doable.
Thank you very much for this solution.

**Comment by jakubsuchygit** [comment]
Is this possible to make this also for the titles of pages? (I mean the buttons in navs)
I though of making switch from ifs for this event, but I am concerned about speed.
For example titles in top_bar_links.html:

 
 Some print of "News".
 
 Some print of "Servers".
 

 
 Some print of "News" in other lang.
 
 Some print of "Servers" in other lang.
 


Will this slower the rendering greatly or not?
Or is there other way?
Thanks

**Comment by VSEphpbb** [comment]
No it won't. Use https://www.phpbb.com/customise/db/extension/pages/support fro support.
