### ISSUE TITLE
[REQ] Page as url link (redirect)

### ISSUE THREAD

**Issue by jakubsuchygit** [phpbb-extensions/pages#57]
Hello,
I would like to suggest to you to add new feature for this extension.
The new feature would work like this:
In ACP there would be choice to add url/link and then when this particular page is clicked in menu it will open URL of added link. So it wouldn't be "static page", but could also be a link. 

It would be same as when I can create reference in actual forum (category, forum, reference) so in similar sense it would be possible for pages.

I hope that you will like this new idea.

Thank you. Biosek.

**Comment by VSEphpbb** [comment]
That simply is not what this extension is intended to do or should be doing.

It's easy to add your own links via an extension, and there may even already be an extension designed to add custom links to the navbars or wherever else.

You can search phpBB.com's extension forums or post a request for such a feature in the extension request forum.
