### ISSUE TITLE
Ignore post char length and edit time limits

### ISSUE THREAD

**Issue by VSEphpbb** [phpbb-extensions/pages#65]
Pages should ignore config settings for posts editing time limits and max/min limits on character count.

https://www.phpbb.com/customise/db/extension/pages/support/topic/140396

**Comment by rxu** [comment]
Every time you force push you got a referencing record here. Fun.

**Comment by VSEphpbb** [comment]
@rxu Just make new commits unless you actually are just making an amendment for a minor mistake.

Also, putting Fixes or Closes and the issue number in a commit message or in the PR's main comment box will allow that PR to automatically close the related issue when it gets merged.
