### ISSUE TITLE
Force server settings not working with this extension?

### ISSUE THREAD

**Issue by jakubsuchybio** [phpbb-extensions/pages#66]
In continuation with issue in here: https://www.phpbb.com/community/viewtopic.php?f=466&t=2302256 we came to conclusion, that there might be problem with pages extension, which creates wrong url links in menus. More information in link above. As partial solution for phpbb core funcionality was to enable forcing server settings. That is why I belive, that pages extension is not using it properly.

**Comment by VSEphpbb** [comment]
Pages does not create links/URLS... phpBB does. If there is any issue, it is with phpBB's framework.
